// Seed categories used only on first load or after "Reset to seed data".
// Feel free to edit — your live data lives in localStorage, not here.
const SEED_CATEGORIES = [
  {
    name: 'Latin — Words',
    cards: [
      ['Deus', 'God'],
      ['Dominus', 'Lord'],
      ['Christus', 'Christ'],
      ['Sanctus', 'Holy'],
      ['Spiritus', 'Spirit, breath'],
      ['Pater', 'Father'],
      ['Filius', 'Son'],
      ['Mater', 'Mother'],
      ['Verbum', 'Word'],
      ['Gloria', 'Glory'],
      ['Pax', 'Peace'],
      ['Vita', 'Life'],
      ['Mors', 'Death'],
      ['Lux', 'Light'],
      ['Aqua', 'Water'],
      ['Panis', 'Bread'],
      ['Vinum', 'Wine'],
      ['Ecclesia', 'Church, assembly'],
      ['Corpus', 'Body'],
      ['Sanguis', 'Blood'],
      ['Anima', 'Soul'],
      ['Caelum', 'Heaven, sky'],
      ['Terra', 'Earth, land'],
      ['Rex', 'King'],
      ['Regnum', 'Kingdom, reign'],
      ['Populus', 'People'],
      ['Veritas', 'Truth'],
      ['Misericordia', 'Mercy'],
      ['Gratia', 'Grace, thanks'],
      ['Peccatum', 'Sin'],
      ['Salus', 'Salvation, health'],
      ['Fides', 'Faith'],
      ['Spes', 'Hope'],
      ['Caritas', 'Love, charity'],
      ['Angelus', 'Angel, messenger'],
      ['Sacerdos', 'Priest'],
      ['Episcopus', 'Bishop'],
      ['Nomen', 'Name'],
      ['Tempus', 'Time'],
      ['Cor', 'Heart'],
    ],
  },
  {
    name: 'Latin — Common phrases',
    cards: [
      ['Pax vobiscum', 'Peace be with you'],
      ['Et cum spiritu tuo', 'And with your spirit'],
      ['Dominus vobiscum', 'The Lord be with you'],
      ['Deo gratias', 'Thanks be to God'],
      ['Kyrie eleison', 'Lord, have mercy (Greek, used in the Latin Mass)'],
      ['Sursum corda', 'Lift up your hearts'],
      ['Habemus ad Dominum', 'We lift them up to the Lord'],
      ['Sanctus, Sanctus, Sanctus', 'Holy, Holy, Holy'],
      ['Agnus Dei', 'Lamb of God'],
      ['Miserere nobis', 'Have mercy on us'],
      ['Dona nobis pacem', 'Grant us peace'],
      ['Requiem aeternam dona eis, Domine', 'Grant them eternal rest, O Lord'],
      ['Ad maiorem Dei gloriam (AMDG)', 'For the greater glory of God'],
      ['Ora pro nobis', 'Pray for us'],
      ['In nomine Patris et Filii et Spiritus Sancti', 'In the name of the Father and of the Son and of the Holy Spirit'],
      ['Gloria in excelsis Deo', 'Glory to God in the highest'],
      ['Mea culpa, mea maxima culpa', 'Through my fault, through my most grievous fault'],
      ['Ecce Agnus Dei', 'Behold the Lamb of God'],
      ['Consummatum est', 'It is finished'],
      ['Ex cathedra', 'From the chair (of teaching authority)'],
      ['Alter Christus', 'Another Christ'],
      ['Ite, missa est', 'Go, it is the dismissal (the Mass has ended)'],
      ['Introibo ad altare Dei', 'I will go up to the altar of God'],
      ['Confiteor', 'I confess'],
      ['Credo', 'I believe'],
      ['Amen', 'So be it / truly'],
      ['Alleluia', 'Praise the Lord (from Hebrew Hallelujah)'],
      ['Hosanna in excelsis', 'Hosanna in the highest'],
    ],
  },
  {
    name: 'Latin — Declensions',
    cards: [
      ['1st declension nominative singular ending', '-a  (e.g. rosa)'],
      ['1st declension genitive singular ending', '-ae  (rosae)'],
      ['1st declension dative singular ending', '-ae  (rosae)'],
      ['1st declension accusative singular ending', '-am  (rosam)'],
      ['1st declension ablative singular ending', '-ā  (rosā)'],
      ['1st declension nominative plural ending', '-ae  (rosae)'],
      ['1st declension genitive plural ending', '-ārum  (rosārum)'],
      ['2nd declension (masc) nominative singular ending', '-us  (dominus)'],
      ['2nd declension (masc) genitive singular ending', '-i  (domini)'],
      ['2nd declension (masc) accusative singular ending', '-um  (dominum)'],
      ['2nd declension (neuter) nominative & accusative singular ending', '-um  (verbum)'],
      ['2nd declension (neuter) nominative & accusative plural ending', '-a  (verba)'],
      ['3rd declension genitive singular ending', '-is  (regis)'],
      ['3rd declension dative singular ending', '-i  (regi)'],
      ['3rd declension accusative singular ending (M/F)', '-em  (regem)'],
      ['3rd declension ablative singular ending', '-e  (rege)'],
      ['3rd declension genitive plural ending', '-um / -ium'],
      ['4th declension nominative singular ending', '-us  (manus)'],
      ['4th declension genitive singular ending', '-ūs  (manūs)'],
      ['5th declension nominative singular ending', '-es  (dies)'],
      ['5th declension genitive singular ending', '-eī / -ēī  (diēī)'],
      ['Genitive of "Deus"', 'Deī'],
      ['Genitive of "Dominus"', 'Domini'],
      ['Genitive of "Christus"', 'Christi'],
      ['Genitive of "Spiritus" (4th decl.)', 'Spiritūs'],
      ['Ablative of "Deus"', 'Deō'],
      ['Vocative of "Dominus"', 'Domine'],
      ['Vocative of "Filius"', 'Filī  (contracted from Filie)'],
    ],
  },
  {
    name: 'Latin — Conjugations',
    cards: [
      ['1st conjugation infinitive ending', '-āre  (amāre — to love)'],
      ['2nd conjugation infinitive ending', '-ēre  (monēre — to warn)'],
      ['3rd conjugation infinitive ending', '-ere  (regere — to rule)'],
      ['4th conjugation infinitive ending', '-īre  (audīre — to hear)'],
      ['amāre — present, 1st person singular', 'amō  (I love)'],
      ['amāre — present, 2nd person singular', 'amās'],
      ['amāre — present, 3rd person singular', 'amat'],
      ['amāre — present, 1st person plural', 'amāmus'],
      ['amāre — present, 2nd person plural', 'amātis'],
      ['amāre — present, 3rd person plural', 'amant'],
      ['monēre — present, 1st person singular', 'moneō'],
      ['monēre — present, 3rd person plural', 'monent'],
      ['regere — present, 1st person singular', 'regō'],
      ['regere — present, 3rd person plural', 'regunt'],
      ['audīre — present, 1st person singular', 'audiō'],
      ['audīre — present, 3rd person plural', 'audiunt'],
      ['esse (to be) — present indicative', 'sum, es, est, sumus, estis, sunt'],
      ['esse — imperfect indicative', 'eram, erās, erat, erāmus, erātis, erant'],
      ['esse — future indicative', 'erō, eris, erit, erimus, eritis, erunt'],
      ['posse (to be able) — 1st person singular present', 'possum'],
      ['ire (to go) — present indicative', 'eō, īs, it, īmus, ītis, eunt'],
      ['Perfect tense — 1st person singular ending', '-ī  (amāvī)'],
      ['Perfect tense — 3rd person plural ending', '-ērunt  (amāvērunt)'],
      ['Passive present — 1st person singular ending (1st conj.)', '-or  (amor — I am loved)'],
      ['Imperative singular of amāre', 'amā  (love!)'],
      ['Imperative plural of amāre', 'amāte'],
    ],
  },
  {
    name: 'AI/ML — Terms',
    cards: [
      ['Gradient descent', 'Iterative optimization that updates parameters in the direction opposite the gradient of the loss.'],
      ['Backpropagation', 'Reverse-mode autodiff: computes gradients of a scalar loss w.r.t. every parameter by applying the chain rule from output back to input.'],
      ['Self-attention', 'Each token computes a weighted sum over all tokens in the sequence, where weights come from query·key dot products passed through softmax.'],
      ['Multi-head attention', 'Runs several attention operations in parallel with different learned projections, then concatenates. Lets the model attend to different subspaces at once.'],
      ['Positional encoding', 'Signal added to token embeddings so the model can distinguish token order. Sinusoidal, learned, RoPE, or ALiBi.'],
      ['RoPE (Rotary Position Embedding)', 'Rotates query/key vectors by an angle proportional to position, so dot products naturally encode relative position. Standard in modern LLMs.'],
      ['Softmax', 'Turns a vector of scores into a probability distribution: exp(x_i) / Σ exp(x_j).'],
      ['Cross-entropy loss', 'Loss for classification: −log p(true class). For LLMs, sums over next-token predictions.'],
      ['Dropout', 'Randomly zeroes activations during training to prevent co-adaptation; a form of regularization.'],
      ['Layer normalization', 'Normalizes activations across the feature dimension per token. Standard in Transformers (often as RMSNorm variant now).'],
      ['Batch normalization', 'Normalizes activations across the batch dimension. Common in CNNs, rare in Transformers.'],
      ['Adam / AdamW', 'Adaptive optimizer using running estimates of first and second moments of gradients. AdamW decouples weight decay from the update.'],
      ['Learning rate warmup', 'Ramps LR from ~0 up to a target over the first N steps to stabilize early training.'],
      ['Tokenization (BPE)', 'Byte-Pair Encoding: iteratively merges the most frequent adjacent byte/character pairs into subword tokens.'],
      ['Context window', 'Max number of tokens a model can attend to at once (input + output).'],
      ['KV cache', 'Cached key/value projections for past tokens so autoregressive generation is O(n) per step instead of O(n²).'],
      ['RLHF (Reinforcement Learning from Human Feedback)', 'Fine-tune a base model against a reward model trained on human preference rankings, typically with PPO.'],
      ['DPO (Direct Preference Optimization)', 'Trains directly on preference pairs without an explicit reward model or RL loop. Simpler and often competitive with RLHF.'],
      ['LoRA (Low-Rank Adaptation)', 'Fine-tune by adding small trainable low-rank matrices A·B to frozen weights, cutting trainable params by 100–1000×.'],
      ['QLoRA', 'LoRA on top of a 4-bit quantized base model. Enables fine-tuning very large models on a single GPU.'],
      ['Quantization (int8 / int4)', 'Store weights (and sometimes activations) in low-bit integers to shrink memory and speed inference, with small accuracy loss.'],
      ['Distillation', 'Train a smaller "student" model to match the outputs (or logits) of a larger "teacher."'],
      ['Chain-of-thought (CoT)', 'Prompting or training that elicits intermediate reasoning steps before the final answer.'],
      ['Zero-shot / few-shot', 'Zero-shot: no examples in prompt. Few-shot: a handful of examples in the prompt to shape behavior.'],
      ['Perplexity', 'exp(mean cross-entropy). Lower is better; interpreted as the effective branching factor of the model.'],
      ['Overfitting', 'Model learns training-set noise; test loss rises while train loss keeps falling.'],
      ['Speculative decoding', 'A small draft model proposes several tokens; the target model verifies them in one forward pass. Speeds up inference.'],
      ['FlashAttention', 'IO-aware attention kernel that avoids materializing the full N×N attention matrix in HBM. Faster and lower memory.'],
      ['Mixture of Experts (MoE)', 'Only a subset of "expert" FFN blocks fire per token via a router, giving high total parameters with low active compute.'],
      ['Prompt caching', 'Provider-side caching of the KV state for a repeated prompt prefix, so subsequent calls skip recomputing it.'],
      ['Temperature', 'Divides logits before softmax. Higher = flatter distribution = more random.'],
      ['Top-p (nucleus) sampling', 'Sample only from the smallest set of tokens whose cumulative probability ≥ p.'],
    ],
  },
  {
    name: 'AI/ML — Architectures',
    cards: [
      ['MLP (Multi-Layer Perceptron)', 'Stack of fully-connected layers with nonlinearities. The universal baseline.'],
      ['CNN (Convolutional Neural Network)', 'Uses learned convolution kernels with weight sharing across spatial positions. Dominant for images before ViT.'],
      ['RNN (Recurrent Neural Network)', 'Processes sequences step-by-step, passing a hidden state forward. Vanishing gradients limit long-range use.'],
      ['LSTM / GRU', 'Gated RNN variants that mitigate vanishing gradients with input/forget/output gates.'],
      ['Transformer', 'Self-attention + FFN blocks with residual connections and layernorm. Backbone of nearly all modern LLMs.'],
      ['Encoder-only Transformer (BERT-style)', 'Bidirectional attention; trained with masked language modeling. Good for embeddings and classification.'],
      ['Decoder-only Transformer (GPT-style)', 'Causal (left-to-right) attention; trained on next-token prediction. Backbone of most generative LLMs.'],
      ['Encoder-decoder Transformer (T5, BART)', 'Separate encoder over input, decoder that attends to encoder outputs. Good for translation and seq2seq.'],
      ['ViT (Vision Transformer)', 'Splits an image into patches, treats them as tokens, and runs a Transformer.'],
      ['Diffusion model', 'Learns to reverse a gradual noising process. Dominant for image/video generation.'],
      ['VAE (Variational Autoencoder)', 'Encoder maps input to a distribution over latents; decoder reconstructs. Trained with reconstruction + KL loss.'],
      ['GAN (Generative Adversarial Network)', 'Generator vs. discriminator, trained in opposition. Sharp samples but tricky training.'],
      ['Mixture of Experts (MoE) Transformer', 'Replaces FFN blocks with a router + N experts; each token uses top-k experts.'],
      ['State Space Model (Mamba, S4)', 'Sequence model with linear-time inference via a learned linear recurrence. Competitive with Transformers at long context.'],
      ['CLIP', 'Dual encoders (image + text) trained with a contrastive loss on image-caption pairs. Enables zero-shot classification.'],
      ['Retrieval-Augmented Generation (RAG)', 'Retrieve relevant docs at inference time, then condition an LLM on them. Not an architecture change per se, but a common pattern.'],
    ],
  },
  {
    name: 'AI/ML — Popular LLMs',
    cards: [
      ['Claude Opus 4.7', 'Anthropic. Frontier model, released 2025. Size undisclosed. Access: Anthropic API, AWS Bedrock, Google Vertex, Claude.ai.'],
      ['Claude Sonnet 4.6', 'Anthropic. Mid-tier frontier model. Size undisclosed. Access: same as Opus.'],
      ['Claude Haiku 4.5', 'Anthropic. Fast/cheap tier. Size undisclosed. Access: same as Opus.'],
      ['GPT-4o', 'OpenAI. Native multimodal (text/image/audio). Size undisclosed. Access: OpenAI API, Azure OpenAI, ChatGPT.'],
      ['GPT-5', 'OpenAI. Frontier model, 2025. Size undisclosed. Access: OpenAI API, ChatGPT.'],
      ['Gemini 2.0 Pro / Flash', 'Google DeepMind. Long context (1M+ tokens). Size undisclosed. Access: Google AI Studio, Vertex AI, Gemini app.'],
      ['Llama 3.1 405B', 'Meta. Open weights. 405B dense parameters. Access: Hugging Face, Meta.ai, hosted by Together, Fireworks, Groq, AWS, etc.'],
      ['Llama 3.3 70B', 'Meta. Open weights. 70B dense. Similar quality to 405B at a fraction of the cost. Same hosts.'],
      ['Llama 3.1 8B', 'Meta. Open weights. 8B dense. The go-to small open model.'],
      ['Mixtral 8x7B', 'Mistral AI. Open weights. MoE: 8 experts × 7B (~47B total, ~13B active per token).'],
      ['Mixtral 8x22B', 'Mistral AI. Open weights. MoE: 8×22B (~141B total, ~39B active).'],
      ['Mistral 7B', 'Mistral AI. Open weights. 7B dense. The reference small model.'],
      ['DeepSeek V3', 'DeepSeek. Open weights. MoE: 671B total, ~37B active per token. Strong reasoning and code.'],
      ['Qwen 2.5 72B', 'Alibaba. Open weights. 72B dense. Full series ranges from 0.5B to 72B.'],
      ['Gemma 2 27B', 'Google. Open weights. 27B dense. Sizes: 2B / 9B / 27B.'],
      ['Phi-3.5 mini', 'Microsoft. Open weights. ~3.8B dense. Punches above its weight on reasoning benchmarks.'],
      ['Grok 3', 'xAI. Size undisclosed. Access: X/Twitter, grok.com, xAI API.'],
      ['Command R+', 'Cohere. Open weights. 104B dense. Tuned for RAG and tool use.'],
    ],
  },
];
