// Seed categories used only on first load or after "Reset to seed data".
// Feel free to edit — your live data lives in localStorage, not here.
//
// Adding categories later? Bump CURRENT_SEED_REVISION below AND tag each new
// category with `since: <that revision>`. On next load, existing users will
// have the new categories added (only) — old ones they've customized or
// deleted are left alone.
const CURRENT_SEED_REVISION = 2;

const SEED_CATEGORIES = [
  {
    name: 'Latin — Words',
    cards: [
      ['Deus', 'God'],
      ['Dominus', 'Lord'],
      ['Christus', 'Christ'],
      ['Sanctus', 'Holy'],
      ['Spiritus', 'Spirit, breath'],
      ['Pater', 'Father'],
      ['Filius', 'Son'],
      ['Mater', 'Mother'],
      ['Verbum', 'Word'],
      ['Gloria', 'Glory'],
      ['Pax', 'Peace'],
      ['Vita', 'Life'],
      ['Mors', 'Death'],
      ['Lux', 'Light'],
      ['Aqua', 'Water'],
      ['Panis', 'Bread'],
      ['Vinum', 'Wine'],
      ['Ecclesia', 'Church, assembly'],
      ['Corpus', 'Body'],
      ['Sanguis', 'Blood'],
      ['Anima', 'Soul'],
      ['Caelum', 'Heaven, sky'],
      ['Terra', 'Earth, land'],
      ['Rex', 'King'],
      ['Regnum', 'Kingdom, reign'],
      ['Populus', 'People'],
      ['Veritas', 'Truth'],
      ['Misericordia', 'Mercy'],
      ['Gratia', 'Grace, thanks'],
      ['Peccatum', 'Sin'],
      ['Salus', 'Salvation, health'],
      ['Fides', 'Faith'],
      ['Spes', 'Hope'],
      ['Caritas', 'Love, charity'],
      ['Angelus', 'Angel, messenger'],
      ['Sacerdos', 'Priest'],
      ['Episcopus', 'Bishop'],
      ['Nomen', 'Name'],
      ['Tempus', 'Time'],
      ['Cor', 'Heart'],
    ],
  },
  {
    name: 'Latin — Common phrases',
    cards: [
      ['Pax vobiscum', 'Peace be with you'],
      ['Et cum spiritu tuo', 'And with your spirit'],
      ['Dominus vobiscum', 'The Lord be with you'],
      ['Deo gratias', 'Thanks be to God'],
      ['Kyrie eleison', 'Lord, have mercy (Greek, used in the Latin Mass)'],
      ['Sursum corda', 'Lift up your hearts'],
      ['Habemus ad Dominum', 'We lift them up to the Lord'],
      ['Sanctus, Sanctus, Sanctus', 'Holy, Holy, Holy'],
      ['Agnus Dei', 'Lamb of God'],
      ['Miserere nobis', 'Have mercy on us'],
      ['Dona nobis pacem', 'Grant us peace'],
      ['Requiem aeternam dona eis, Domine', 'Grant them eternal rest, O Lord'],
      ['Ad maiorem Dei gloriam (AMDG)', 'For the greater glory of God'],
      ['Ora pro nobis', 'Pray for us'],
      ['In nomine Patris et Filii et Spiritus Sancti', 'In the name of the Father and of the Son and of the Holy Spirit'],
      ['Gloria in excelsis Deo', 'Glory to God in the highest'],
      ['Mea culpa, mea maxima culpa', 'Through my fault, through my most grievous fault'],
      ['Ecce Agnus Dei', 'Behold the Lamb of God'],
      ['Consummatum est', 'It is finished'],
      ['Ex cathedra', 'From the chair (of teaching authority)'],
      ['Alter Christus', 'Another Christ'],
      ['Ite, missa est', 'Go, it is the dismissal (the Mass has ended)'],
      ['Introibo ad altare Dei', 'I will go up to the altar of God'],
      ['Confiteor', 'I confess'],
      ['Credo', 'I believe'],
      ['Amen', 'So be it / truly'],
      ['Alleluia', 'Praise the Lord (from Hebrew Hallelujah)'],
      ['Hosanna in excelsis', 'Hosanna in the highest'],
    ],
  },
  {
    name: 'Latin — Declensions',
    cards: [
      ['1st declension nominative singular ending', '-a  (e.g. rosa)'],
      ['1st declension genitive singular ending', '-ae  (rosae)'],
      ['1st declension dative singular ending', '-ae  (rosae)'],
      ['1st declension accusative singular ending', '-am  (rosam)'],
      ['1st declension ablative singular ending', '-ā  (rosā)'],
      ['1st declension nominative plural ending', '-ae  (rosae)'],
      ['1st declension genitive plural ending', '-ārum  (rosārum)'],
      ['2nd declension (masc) nominative singular ending', '-us  (dominus)'],
      ['2nd declension (masc) genitive singular ending', '-i  (domini)'],
      ['2nd declension (masc) accusative singular ending', '-um  (dominum)'],
      ['2nd declension (neuter) nominative & accusative singular ending', '-um  (verbum)'],
      ['2nd declension (neuter) nominative & accusative plural ending', '-a  (verba)'],
      ['3rd declension genitive singular ending', '-is  (regis)'],
      ['3rd declension dative singular ending', '-i  (regi)'],
      ['3rd declension accusative singular ending (M/F)', '-em  (regem)'],
      ['3rd declension ablative singular ending', '-e  (rege)'],
      ['3rd declension genitive plural ending', '-um / -ium'],
      ['4th declension nominative singular ending', '-us  (manus)'],
      ['4th declension genitive singular ending', '-ūs  (manūs)'],
      ['5th declension nominative singular ending', '-es  (dies)'],
      ['5th declension genitive singular ending', '-eī / -ēī  (diēī)'],
      ['Genitive of "Deus"', 'Deī'],
      ['Genitive of "Dominus"', 'Domini'],
      ['Genitive of "Christus"', 'Christi'],
      ['Genitive of "Spiritus" (4th decl.)', 'Spiritūs'],
      ['Ablative of "Deus"', 'Deō'],
      ['Vocative of "Dominus"', 'Domine'],
      ['Vocative of "Filius"', 'Filī  (contracted from Filie)'],
    ],
  },
  {
    name: 'Latin — Conjugations',
    cards: [
      ['1st conjugation infinitive ending', '-āre  (amāre — to love)'],
      ['2nd conjugation infinitive ending', '-ēre  (monēre — to warn)'],
      ['3rd conjugation infinitive ending', '-ere  (regere — to rule)'],
      ['4th conjugation infinitive ending', '-īre  (audīre — to hear)'],
      ['amāre — present, 1st person singular', 'amō  (I love)'],
      ['amāre — present, 2nd person singular', 'amās'],
      ['amāre — present, 3rd person singular', 'amat'],
      ['amāre — present, 1st person plural', 'amāmus'],
      ['amāre — present, 2nd person plural', 'amātis'],
      ['amāre — present, 3rd person plural', 'amant'],
      ['monēre — present, 1st person singular', 'moneō'],
      ['monēre — present, 3rd person plural', 'monent'],
      ['regere — present, 1st person singular', 'regō'],
      ['regere — present, 3rd person plural', 'regunt'],
      ['audīre — present, 1st person singular', 'audiō'],
      ['audīre — present, 3rd person plural', 'audiunt'],
      ['esse (to be) — present indicative', 'sum, es, est, sumus, estis, sunt'],
      ['esse — imperfect indicative', 'eram, erās, erat, erāmus, erātis, erant'],
      ['esse — future indicative', 'erō, eris, erit, erimus, eritis, erunt'],
      ['posse (to be able) — 1st person singular present', 'possum'],
      ['ire (to go) — present indicative', 'eō, īs, it, īmus, ītis, eunt'],
      ['Perfect tense — 1st person singular ending', '-ī  (amāvī)'],
      ['Perfect tense — 3rd person plural ending', '-ērunt  (amāvērunt)'],
      ['Passive present — 1st person singular ending (1st conj.)', '-or  (amor — I am loved)'],
      ['Imperative singular of amāre', 'amā  (love!)'],
      ['Imperative plural of amāre', 'amāte'],
    ],
  },
  {
    name: 'AI/ML — Terms',
    cards: [
      ['Gradient descent', 'Iterative optimization that updates parameters in the direction opposite the gradient of the loss.'],
      ['Backpropagation', 'Reverse-mode autodiff: computes gradients of a scalar loss w.r.t. every parameter by applying the chain rule from output back to input.'],
      ['Self-attention', 'Each token computes a weighted sum over all tokens in the sequence, where weights come from query·key dot products passed through softmax.'],
      ['Multi-head attention', 'Runs several attention operations in parallel with different learned projections, then concatenates. Lets the model attend to different subspaces at once.'],
      ['Positional encoding', 'Signal added to token embeddings so the model can distinguish token order. Sinusoidal, learned, RoPE, or ALiBi.'],
      ['RoPE (Rotary Position Embedding)', 'Rotates query/key vectors by an angle proportional to position, so dot products naturally encode relative position. Standard in modern LLMs.'],
      ['Softmax', 'Turns a vector of scores into a probability distribution: exp(x_i) / Σ exp(x_j).'],
      ['Cross-entropy loss', 'Loss for classification: −log p(true class). For LLMs, sums over next-token predictions.'],
      ['Dropout', 'Randomly zeroes activations during training to prevent co-adaptation; a form of regularization.'],
      ['Layer normalization', 'Normalizes activations across the feature dimension per token. Standard in Transformers (often as RMSNorm variant now).'],
      ['Batch normalization', 'Normalizes activations across the batch dimension. Common in CNNs, rare in Transformers.'],
      ['Adam / AdamW', 'Adaptive optimizer using running estimates of first and second moments of gradients. AdamW decouples weight decay from the update.'],
      ['Learning rate warmup', 'Ramps LR from ~0 up to a target over the first N steps to stabilize early training.'],
      ['Tokenization (BPE)', 'Byte-Pair Encoding: iteratively merges the most frequent adjacent byte/character pairs into subword tokens.'],
      ['Context window', 'Max number of tokens a model can attend to at once (input + output).'],
      ['KV cache', 'Cached key/value projections for past tokens so autoregressive generation is O(n) per step instead of O(n²).'],
      ['RLHF (Reinforcement Learning from Human Feedback)', 'Fine-tune a base model against a reward model trained on human preference rankings, typically with PPO.'],
      ['DPO (Direct Preference Optimization)', 'Trains directly on preference pairs without an explicit reward model or RL loop. Simpler and often competitive with RLHF.'],
      ['LoRA (Low-Rank Adaptation)', 'Fine-tune by adding small trainable low-rank matrices A·B to frozen weights, cutting trainable params by 100–1000×.'],
      ['QLoRA', 'LoRA on top of a 4-bit quantized base model. Enables fine-tuning very large models on a single GPU.'],
      ['Quantization (int8 / int4)', 'Store weights (and sometimes activations) in low-bit integers to shrink memory and speed inference, with small accuracy loss.'],
      ['Distillation', 'Train a smaller "student" model to match the outputs (or logits) of a larger "teacher."'],
      ['Chain-of-thought (CoT)', 'Prompting or training that elicits intermediate reasoning steps before the final answer.'],
      ['Zero-shot / few-shot', 'Zero-shot: no examples in prompt. Few-shot: a handful of examples in the prompt to shape behavior.'],
      ['Perplexity', 'exp(mean cross-entropy). Lower is better; interpreted as the effective branching factor of the model.'],
      ['Overfitting', 'Model learns training-set noise; test loss rises while train loss keeps falling.'],
      ['Speculative decoding', 'A small draft model proposes several tokens; the target model verifies them in one forward pass. Speeds up inference.'],
      ['FlashAttention', 'IO-aware attention kernel that avoids materializing the full N×N attention matrix in HBM. Faster and lower memory.'],
      ['Mixture of Experts (MoE)', 'Only a subset of "expert" FFN blocks fire per token via a router, giving high total parameters with low active compute.'],
      ['Prompt caching', 'Provider-side caching of the KV state for a repeated prompt prefix, so subsequent calls skip recomputing it.'],
      ['Temperature', 'Divides logits before softmax. Higher = flatter distribution = more random.'],
      ['Top-p (nucleus) sampling', 'Sample only from the smallest set of tokens whose cumulative probability ≥ p.'],
    ],
  },
  {
    name: 'AI/ML — Architectures',
    cards: [
      ['MLP (Multi-Layer Perceptron)', 'Stack of fully-connected layers with nonlinearities. The universal baseline.'],
      ['CNN (Convolutional Neural Network)', 'Uses learned convolution kernels with weight sharing across spatial positions. Dominant for images before ViT.'],
      ['RNN (Recurrent Neural Network)', 'Processes sequences step-by-step, passing a hidden state forward. Vanishing gradients limit long-range use.'],
      ['LSTM / GRU', 'Gated RNN variants that mitigate vanishing gradients with input/forget/output gates.'],
      ['Transformer', 'Self-attention + FFN blocks with residual connections and layernorm. Backbone of nearly all modern LLMs.'],
      ['Encoder-only Transformer (BERT-style)', 'Bidirectional attention; trained with masked language modeling. Good for embeddings and classification.'],
      ['Decoder-only Transformer (GPT-style)', 'Causal (left-to-right) attention; trained on next-token prediction. Backbone of most generative LLMs.'],
      ['Encoder-decoder Transformer (T5, BART)', 'Separate encoder over input, decoder that attends to encoder outputs. Good for translation and seq2seq.'],
      ['ViT (Vision Transformer)', 'Splits an image into patches, treats them as tokens, and runs a Transformer.'],
      ['Diffusion model', 'Learns to reverse a gradual noising process. Dominant for image/video generation.'],
      ['VAE (Variational Autoencoder)', 'Encoder maps input to a distribution over latents; decoder reconstructs. Trained with reconstruction + KL loss.'],
      ['GAN (Generative Adversarial Network)', 'Generator vs. discriminator, trained in opposition. Sharp samples but tricky training.'],
      ['Mixture of Experts (MoE) Transformer', 'Replaces FFN blocks with a router + N experts; each token uses top-k experts.'],
      ['State Space Model (Mamba, S4)', 'Sequence model with linear-time inference via a learned linear recurrence. Competitive with Transformers at long context.'],
      ['CLIP', 'Dual encoders (image + text) trained with a contrastive loss on image-caption pairs. Enables zero-shot classification.'],
      ['Retrieval-Augmented Generation (RAG)', 'Retrieve relevant docs at inference time, then condition an LLM on them. Not an architecture change per se, but a common pattern.'],
    ],
  },
  {
    name: 'AI/ML — Popular LLMs',
    cards: [
      ['Claude Opus 4.7', 'Anthropic. Frontier model, released 2025. Size undisclosed. Access: Anthropic API, AWS Bedrock, Google Vertex, Claude.ai.'],
      ['Claude Sonnet 4.6', 'Anthropic. Mid-tier frontier model. Size undisclosed. Access: same as Opus.'],
      ['Claude Haiku 4.5', 'Anthropic. Fast/cheap tier. Size undisclosed. Access: same as Opus.'],
      ['GPT-4o', 'OpenAI. Native multimodal (text/image/audio). Size undisclosed. Access: OpenAI API, Azure OpenAI, ChatGPT.'],
      ['GPT-5', 'OpenAI. Frontier model, 2025. Size undisclosed. Access: OpenAI API, ChatGPT.'],
      ['Gemini 2.0 Pro / Flash', 'Google DeepMind. Long context (1M+ tokens). Size undisclosed. Access: Google AI Studio, Vertex AI, Gemini app.'],
      ['Llama 3.1 405B', 'Meta. Open weights. 405B dense parameters. Access: Hugging Face, Meta.ai, hosted by Together, Fireworks, Groq, AWS, etc.'],
      ['Llama 3.3 70B', 'Meta. Open weights. 70B dense. Similar quality to 405B at a fraction of the cost. Same hosts.'],
      ['Llama 3.1 8B', 'Meta. Open weights. 8B dense. The go-to small open model.'],
      ['Mixtral 8x7B', 'Mistral AI. Open weights. MoE: 8 experts × 7B (~47B total, ~13B active per token).'],
      ['Mixtral 8x22B', 'Mistral AI. Open weights. MoE: 8×22B (~141B total, ~39B active).'],
      ['Mistral 7B', 'Mistral AI. Open weights. 7B dense. The reference small model.'],
      ['DeepSeek V3', 'DeepSeek. Open weights. MoE: 671B total, ~37B active per token. Strong reasoning and code.'],
      ['Qwen 2.5 72B', 'Alibaba. Open weights. 72B dense. Full series ranges from 0.5B to 72B.'],
      ['Gemma 2 27B', 'Google. Open weights. 27B dense. Sizes: 2B / 9B / 27B.'],
      ['Phi-3.5 mini', 'Microsoft. Open weights. ~3.8B dense. Punches above its weight on reasoning benchmarks.'],
      ['Grok 3', 'xAI. Size undisclosed. Access: X/Twitter, grok.com, xAI API.'],
      ['Command R+', 'Cohere. Open weights. 104B dense. Tuned for RAG and tool use.'],
    ],
  },
  {
    name: 'Cancer Biology — Hallmarks & core concepts',
    since: 1,
    cards: [
      ['Sustained proliferative signaling', 'Cancer cells produce their own growth-factor ligands or become insensitive to normal proliferation controls, driving continuous cell division.'],
      ['Evading growth suppressors', 'Loss of tumor suppressor function (e.g. TP53, RB1) removes brakes on the cell cycle and contact inhibition.'],
      ['Resisting cell death', 'Mutations (e.g. Bcl-2 overexpression, TP53 loss) block apoptosis so damaged cells that should die survive.'],
      ['Enabling replicative immortality', 'Reactivation of telomerase (TERT) prevents telomere shortening, letting cells avoid replicative senescence.'],
      ['Inducing angiogenesis', 'Tumors secrete VEGF and other factors to sprout new blood vessels for oxygen and nutrients.'],
      ['Activating invasion and metastasis', 'Loss of E-cadherin, EMT, and matrix-degrading enzymes let cells invade and colonize distant sites.'],
      ['Reprogramming energy metabolism (Warburg effect)', 'Cancer cells favor glycolysis + lactate fermentation even in the presence of oxygen. Trades ATP efficiency for fast biosynthesis of NADH, ribose, amino acids.'],
      ['Avoiding immune destruction', 'Tumors express PD-L1, downregulate MHC-I, and recruit Tregs/MDSCs to evade T-cell killing.'],
      ['Genome instability (enabling hallmark)', 'Defects in DNA repair or mitotic checkpoints let mutations accumulate — the engine that generates the other hallmarks.'],
      ['Tumor-promoting inflammation (enabling hallmark)', 'Chronic inflammation supplies growth factors, ROS, and survival signals that promote cancer.'],
      ['Unlocking phenotypic plasticity (2022 hallmark)', 'Cells switch differentiation states or de-differentiate, adopting new phenotypes without new mutations.'],
      ['Nonmutational epigenetic reprogramming (2022)', 'Heritable changes in gene expression (DNA methylation, histone marks, chromatin state) without underlying DNA sequence changes.'],
      ['Polymorphic microbiomes (2022)', 'Gut and tumor microbiome composition modulates cancer development, progression, and therapy response — especially immunotherapy.'],
      ['Senescent cells (2022 hallmark)', 'Non-dividing but metabolically active cells in the TME secrete SASP factors (cytokines, proteases) that can promote neighboring tumor growth.'],
      ['Apoptosis', 'Programmed cell death via intrinsic (mitochondrial: BAX/BAK → cytochrome c → APAF-1 → caspase-9) or extrinsic (death receptor → FADD → caspase-8) pathways, both converging on effector caspases 3/6/7.'],
      ['Autophagy', '"Self-eating" — cells sequester and degrade organelles/proteins in autophagosomes. Can promote survival under stress (helping cancer cells) or trigger death.'],
      ['Ferroptosis', 'Iron-dependent regulated cell death from lipid peroxidation. GPX4 dependent. Being explored as an anti-cancer therapy target.'],
      ['Telomeres / telomerase', 'Telomeres cap chromosome ends and shorten each division. Telomerase (TERT catalytic + TERC RNA template) rebuilds them; reactivated in ~90% of cancers, often via TERT promoter mutations.'],
      ['EMT (epithelial-mesenchymal transition)', 'Epithelial cells lose E-cadherin and cell polarity, gain mesenchymal markers (vimentin, N-cadherin), acquire motility. Driven by SNAIL/SLUG/TWIST/ZEB1. Key step in metastasis.'],
      ['Metastatic cascade', 'Local invasion → intravasation → survival in circulation → extravasation → micrometastasis → colonization at distant site. Highly inefficient — <0.01% of circulating tumor cells form macrometastases.'],
      ['Cancer stem cells (CSCs)', 'Rare tumor subpopulation with self-renewal and differentiation capacity. Thought to drive tumor initiation, therapy resistance (quiescence), and recurrence.'],
      ['Tumor microenvironment (TME)', 'Non-cancer components: cancer-associated fibroblasts, endothelial cells, immune cells, ECM, cytokines. Co-evolves with the tumor and shapes therapy response.'],
      ['Two-hit hypothesis (Knudson)', 'A tumor suppressor typically requires both alleles inactivated to lose function. First hit can be inherited (as in retinoblastoma) or somatic — the second is usually LOH.'],
      ['Loss of heterozygosity (LOH)', 'Loss of the remaining wild-type allele of a tumor suppressor (via deletion, mitotic recombination, gene conversion). Often unmasks an underlying inherited mutation.'],
      ['TNM staging', 'Tumor size and extent (T), lymph Node involvement (N), distant Metastasis (M). Combined into overall stage 0–IV. Standardized by AJCC/UICC.'],
      ['Tumor grade vs stage', 'Grade = how abnormal cells look microscopically (differentiation). Stage = how far the cancer has spread anatomically. High grade + low stage is possible and vice versa.'],
      ['Contact inhibition', 'Normal cells stop dividing when they touch neighbors. Cancer cells lose this and pile up in culture — a defining transformation phenotype.'],
      ['Anchorage-independent growth', 'Ability to grow without attachment to a substrate (e.g. in soft agar). Classic in vitro marker of transformed cells.'],
      ['Driver vs passenger mutations', 'Driver: confers a selective growth advantage, actively contributes to cancer. Passenger: hitchhikes along, no functional effect. Most somatic mutations in a tumor are passengers.'],
      ['Clonal evolution', 'Cancer as a Darwinian process: successive mutations create subclones under selection pressure from the TME and therapy. Explains heterogeneity and resistance.'],
    ],
  },
  {
    name: 'Cancer Biology — Oncogenes & tumor suppressors',
    since: 1,
    cards: [
      ['Oncogene vs tumor suppressor', 'Oncogene: gain-of-function drives cancer (one mutant allele enough — dominant at cellular level). Tumor suppressor: loss-of-function drives cancer (usually needs both alleles — recessive).'],
      ['Proto-oncogene', 'Normal cellular gene whose activating mutation, amplification, or translocation converts it into an oncogene.'],
      ['MYC (c-MYC)', 'Transcription factor driving cell growth, metabolism, and biosynthesis. Amplified or translocated in many cancers. Classic: Burkitt lymphoma t(8;14) puts MYC under Ig heavy chain enhancer.'],
      ['RAS family (KRAS, NRAS, HRAS)', 'Small GTPases upstream of MAPK and PI3K. Point mutations at G12/G13/Q61 lock RAS in GTP-bound "on" state. KRAS mutated in ~30% of all cancers (pancreatic ~95%, colon ~45%, lung ~30%).'],
      ['BRAF (V600E)', 'Serine/threonine kinase in MAPK pathway downstream of RAS. V600E mutation is constitutively active. ~50% of melanomas; also colorectal, thyroid, hairy cell leukemia.'],
      ['EGFR', 'Receptor tyrosine kinase (ErbB family). Activating mutations (exon 19 del, L858R) drive ~15% of non-squamous NSCLC (higher in East Asian, non-smoker, female). Targeted by erlotinib, gefitinib, osimertinib.'],
      ['HER2 / ERBB2', 'Receptor tyrosine kinase, no known ligand — signals via heterodimerization. Amplified in ~20% of breast cancers and some gastric. Targeted by trastuzumab, pertuzumab, T-DM1, T-DXd.'],
      ['ALK', 'Anaplastic lymphoma kinase. EML4-ALK fusion in ~5% of NSCLC. Targeted sequentially by crizotinib → alectinib/ceritinib → lorlatinib as resistance emerges.'],
      ['BCR-ABL', 't(9;22) Philadelphia chromosome creates a constitutively active tyrosine kinase fusion. Defines CML and a subset of ALL. Imatinib (Gleevec) was the first targeted cancer therapy.'],
      ['PIK3CA', 'Encodes p110α catalytic subunit of PI3K. Hotspot mutations (E545K, H1047R) common in breast, colorectal, endometrial. Targeted by alpelisib in HR+ breast cancer.'],
      ['CDK4/6', 'Cyclin-dependent kinases driving G1→S transition by phosphorylating Rb. Overactivated in cancer via CCND1 amplification or CDKN2A loss. Targeted by palbociclib, ribociclib, abemaciclib.'],
      ['MDM2', 'E3 ubiquitin ligase that targets TP53 for degradation. Amplified in ~10% of sarcomas, effectively inactivating wild-type p53. MDM2 inhibitors in trials.'],
      ['Bcl-2', 'Anti-apoptotic mitochondrial protein. Overexpression via t(14;18) causes follicular lymphoma. Targeted by venetoclax (BH3 mimetic) — approved for CLL and AML.'],
      ['TP53', '"Guardian of the genome." Transcription factor activated by DNA damage or oncogene stress; induces cell cycle arrest (p21), DNA repair, apoptosis (PUMA/BAX), senescence. Mutated in >50% of all human cancers.'],
      ['Li-Fraumeni syndrome', 'Germline TP53 mutation. Very high lifetime risk of sarcomas, premenopausal breast cancer, brain tumors, leukemia, adrenocortical carcinoma.'],
      ['RB1 (retinoblastoma)', 'First tumor suppressor identified. Binds E2F to block G1→S transition. Inherited biallelic loss → retinoblastoma; RB pathway inactivated (directly or indirectly) in nearly all cancers.'],
      ['APC', 'Negative regulator of β-catenin in the Wnt pathway (part of the destruction complex). Germline loss = FAP (thousands of colon polyps → colon cancer). Somatic APC loss in >80% of sporadic colorectal cancers — the initiating event.'],
      ['BRCA1 / BRCA2', 'Essential for homologous recombination repair of DNA double-strand breaks. Germline mutations → high breast, ovarian, pancreatic, prostate cancer risk. Basis for PARP inhibitor synthetic lethality.'],
      ['PTEN', 'Lipid phosphatase that reverses PI3K by converting PIP3 → PIP2. Frequently lost in endometrial, prostate, glioblastoma, breast. Germline loss = Cowden syndrome.'],
      ['VHL', 'E3 ligase for HIF-α. Loss stabilizes HIF, driving VEGF and other hypoxia-response genes. Germline loss = von Hippel-Lindau syndrome; somatic loss in most clear cell renal cell carcinomas.'],
      ['CDKN2A (p16INK4a / p14ARF)', 'One locus, two proteins from alternate reading frames: p16 inhibits CDK4/6 (Rb arm), p14ARF stabilizes p53 (p53 arm). Frequently deleted in melanoma, pancreatic, glioblastoma — hits both arms.'],
      ['NF1', 'RAS-GAP: turns off RAS by stimulating its GTPase activity. Germline loss = neurofibromatosis type 1 (neurofibromas, café-au-lait spots, MPNST risk). Somatic loss activates RAS/MAPK.'],
      ['NF2 (merlin)', 'Upstream regulator of the Hippo pathway. Germline loss = neurofibromatosis type 2 (bilateral vestibular schwannomas, meningiomas).'],
      ['Lynch syndrome (MLH1/MSH2/MSH6/PMS2)', 'Germline loss of a mismatch repair gene. Yields microsatellite-unstable (MSI-H) tumors, especially colorectal and endometrial. MSI-H tumors respond strongly to immune checkpoint blockade.'],
      ['SMAD4 (DPC4)', 'Central mediator of TGF-β signaling. Lost in ~50% of pancreatic ductal adenocarcinomas.'],
      ['ATM', 'Kinase in the DNA damage response, activated by double-strand breaks; phosphorylates CHK2, p53, BRCA1. Germline loss = ataxia-telangiectasia; heterozygous carriers have elevated breast cancer risk.'],
      ['Retinoblastoma (Rb) pathway', 'Cyclin D–CDK4/6 phosphorylates Rb → releases E2F → S-phase genes on. Dysregulated (usually via CDKN2A loss, CCND1 gain, or RB1 loss) in nearly all cancers.'],
      ['JAK2 V617F', 'Constitutively active kinase mutation. Defines most polycythemia vera and drives essential thrombocythemia and primary myelofibrosis (myeloproliferative neoplasms).'],
      ['IDH1 / IDH2 mutations', 'Neomorphic mutations produce oncometabolite 2-hydroxyglutarate, which inhibits α-KG–dependent dioxygenases → hypermethylation. Common in low-grade gliomas, AML, chondrosarcoma. Targeted by ivosidenib, enasidenib.'],
    ],
  },
  {
    name: 'Cancer Biology — Signaling pathways',
    since: 1,
    cards: [
      ['RAS/RAF/MEK/ERK (MAPK) pathway', 'Growth factor → RTK → GRB2/SOS → RAS-GTP → RAF → MEK → ERK → transcription (MYC, cyclin D). Hyperactivated in most cancers, often by RAS, BRAF, or upstream RTK mutations.'],
      ['PI3K/AKT/mTOR pathway', 'Growth factor → RTK → PI3K → PIP3 → PDK1/AKT activation → mTORC1 → protein synthesis, growth, metabolism. Opposed by PTEN. Hyperactivated in ~50% of cancers.'],
      ['Wnt/β-catenin pathway', 'Without Wnt: APC/AXIN/GSK3β destruction complex phosphorylates β-catenin → degradation. With Wnt: complex disassembles → β-catenin stabilized → nuclear → TCF/LEF transcription. APC loss constitutively activates.'],
      ['Hedgehog pathway', 'Ligand (SHH) binds PTCH1, releasing SMO from inhibition → GLI transcription factors. Loss of PTCH1 or activating SMO mutations drive basal cell carcinoma and medulloblastoma. Vismodegib targets SMO.'],
      ['Notch pathway', 'Direct receptor-ligand contact triggers γ-secretase cleavage of NOTCH → NICD → nuclear transcription with RBPJ/CSL. Context-dependent: oncogenic in T-ALL (activating NOTCH1), tumor-suppressive in skin.'],
      ['TGF-β / SMAD pathway', 'TGF-β → TGFBR complex → phosphorylates SMAD2/3 → binds SMAD4 → nuclear transcription. Growth-suppressive in normal/early tumor cells; switches to pro-invasion/pro-metastasis later ("TGF-β paradox").'],
      ['JAK/STAT pathway', 'Cytokine → receptor dimerization → JAK phosphorylates STAT → STAT dimerizes → nuclear transcription. JAK2 V617F drives myeloproliferative neoplasms; targeted by ruxolitinib.'],
      ['NF-κB pathway', 'Stress/cytokines → IKK complex phosphorylates IκB → IκB ubiquitinated + degraded → NF-κB nuclear → survival/inflammation genes. Constitutively active in many lymphomas and inflammation-driven cancers.'],
      ['Hippo / YAP-TAZ pathway', 'MST1/2 → LATS1/2 → phosphorylate YAP/TAZ → cytoplasmic retention and degradation. Loss of Hippo signaling → YAP/TAZ nuclear → TEAD transcription → proliferation, stemness. Linked to organ size control.'],
      ['p53 pathway', 'DNA damage / oncogene stress → ATM/ATR/CHK → p53 stabilization → p21 (cell cycle arrest), PUMA/BAX/NOXA (apoptosis), MDM2 (feedback), GADD45. Inactivated in most cancers, directly or via MDM2 amplification.'],
      ['Rb / E2F pathway', 'Hypophosphorylated Rb binds and inhibits E2F. CDK4/6-cyclin D phosphorylates Rb → releases E2F → S-phase gene transcription. G1/S restriction point — the "commitment" to divide.'],
      ['DNA damage response (DDR)', 'Sensors (MRN/ATM for DSBs, RPA/ATR for ssDNA/stalled forks) → transducers (CHK1/CHK2) → effectors (p53, CDC25 inhibition, repair, apoptosis). Deficiencies are exploitable by DNA-damaging drugs.'],
      ['G1/S checkpoint', 'Rb-E2F restriction point. Checks for DNA damage and adequate growth signals before committing to DNA synthesis. p53-p21 axis blocks CDK2-cyclin E if damage detected.'],
      ['G2/M checkpoint', 'ATM/ATR → CHK1/CHK2 → phosphorylate/inhibit CDC25 → keep CDK1-cyclin B inactive. Ensures DNA is fully replicated and undamaged before mitosis.'],
      ['Spindle assembly checkpoint (SAC)', 'MAD/BUB proteins delay anaphase until all kinetochores are attached to spindle microtubules with proper tension. Defects → aneuploidy, a hallmark of cancer.'],
      ['Homologous recombination (HR)', 'High-fidelity double-strand break repair using a sister chromatid template. BRCA1/BRCA2/RAD51-dependent, restricted to S/G2. Defective HR → PARP inhibitor sensitivity.'],
      ['Non-homologous end joining (NHEJ)', 'Error-prone DSB repair active throughout the cell cycle. Ku70/Ku80 → DNA-PKcs → ligase IV/XRCC4. Backup when HR is unavailable; introduces small indels.'],
      ['Mismatch repair (MMR)', 'MLH1/MSH2/MSH6/PMS2 detect and fix base mismatches from replication. Loss → microsatellite instability (MSI), Lynch syndrome, high tumor mutation burden, and strong ICI responses.'],
      ['Nucleotide excision repair (NER)', 'Removes bulky DNA lesions (UV thymine dimers, adducts). Loss = xeroderma pigmentosum, extreme UV sensitivity, skin cancer risk.'],
      ['Base excision repair (BER)', 'Fixes small base lesions (oxidation, alkylation, deamination). Uses glycosylases + PARP + polymerase β. PARP inhibitors trap PARP1 on BER intermediates → DSBs.'],
    ],
  },
  {
    name: 'Cancer Biology — Therapies & drug targets',
    since: 1,
    cards: [
      ['Chemotherapy', 'Broadly cytotoxic drugs targeting rapidly dividing cells: alkylators (cyclophosphamide), antimetabolites (5-FU, methotrexate), taxanes (paclitaxel), platinum (cisplatin), anthracyclines (doxorubicin). Non-selective — hence classic hair/gut/marrow side effects.'],
      ['Targeted therapy', 'Small molecules or antibodies against specific molecular drivers (mutant kinases, receptor amplifications, fusion proteins). Requires matching a patient to a biomarker.'],
      ['Immunotherapy', 'Therapies that engage the immune system: checkpoint inhibitors, CAR-T, bispecific T-cell engagers, cancer vaccines, cytokines, oncolytic viruses.'],
      ['Imatinib (Gleevec)', 'First targeted cancer drug (2001). Small-molecule BCR-ABL kinase inhibitor. Transformed CML from a fatal disease to a chronic one. Also active against KIT (GIST) and PDGFR.'],
      ['Trastuzumab (Herceptin)', 'Monoclonal antibody against HER2. Used in HER2-amplified breast and gastric cancers. Basis for T-DM1 (Kadcyla) and T-DXd (Enhertu) antibody-drug conjugates.'],
      ['EGFR TKIs', 'Erlotinib, gefitinib (1st-gen) → afatinib (2nd, irreversible) → osimertinib (3rd, active against T790M resistance mutation, current 1st-line). Used in EGFR-mutant NSCLC.'],
      ['ALK TKIs', 'Crizotinib (1st) → alectinib, ceritinib, brigatinib → lorlatinib. Alectinib is now standard 1st-line for ALK+ NSCLC. Sequential switching as resistance mutations emerge.'],
      ['BRAF + MEK combo (vemurafenib/dabrafenib + trametinib)', 'Dual inhibition of BRAF V600E and downstream MEK. Standard for BRAF-mutant melanoma; combo better than BRAF alone due to paradoxical MAPK reactivation and delayed resistance.'],
      ['PARP inhibitors (olaparib, rucaparib, niraparib, talazoparib)', 'Block PARP-mediated single-strand break repair and trap PARP1 on DNA. Synthetic lethal with BRCA1/2 loss (HR-deficient tumors). Used in BRCA/HRD ovarian, breast, prostate, pancreatic.'],
      ['CDK4/6 inhibitors (palbociclib, ribociclib, abemaciclib)', 'Block G1→S transition by preventing Rb phosphorylation. Combined with endocrine therapy (aromatase inhibitor or fulvestrant) in HR+/HER2- breast cancer — major PFS gains.'],
      ['mTOR inhibitors (everolimus, temsirolimus)', 'Rapamycin analogs (rapalogs) blocking mTORC1. Used in RCC, HR+ breast (with exemestane), neuroendocrine tumors, TSC-related tumors.'],
      ['Bevacizumab (Avastin)', 'Anti-VEGF monoclonal antibody, blocks angiogenesis. Broad use across colorectal, NSCLC, glioblastoma, ovarian, RCC — usually with chemo backbone.'],
      ['Rituximab', 'Anti-CD20 monoclonal antibody targeting B cells. Backbone of B-cell lymphoma and CLL therapy (R-CHOP for DLBCL). Also used in autoimmune disease.'],
      ['Immune checkpoint inhibitors (ICIs)', 'Antibodies that block inhibitory receptors on T cells or their ligands on tumors, releasing anti-tumor immunity. Backbone of modern immuno-oncology across ~20 tumor types.'],
      ['Anti-PD-1 (pembrolizumab, nivolumab)', 'Block PD-1 on activated T cells so tumor-expressed PD-L1 can\'t silence them. Approved across dozens of cancer types, often with biomarkers (PD-L1 expression, MSI-H, TMB-high).'],
      ['Anti-PD-L1 (atezolizumab, durvalumab, avelumab)', 'Block PD-L1 on tumor and myeloid cells from engaging PD-1. Approved in NSCLC, urothelial, TNBC, HCC, SCLC.'],
      ['Anti-CTLA-4 (ipilimumab)', 'First checkpoint inhibitor approved (2011, melanoma). Blocks CTLA-4 on T cells, allowing CD28 costimulation. Often combined with anti-PD-1 (nivo+ipi) — higher response, higher toxicity.'],
      ['CAR-T therapy', 'Patient T cells engineered ex vivo with a chimeric antigen receptor (extracellular scFv + CD3ζ + costimulatory domain, usually 4-1BB or CD28), expanded, and reinfused. Approved: anti-CD19 (B-ALL, DLBCL, FL), anti-BCMA (myeloma).'],
      ['Antibody-drug conjugates (ADCs)', 'Monoclonal antibody linked to a cytotoxic payload via a cleavable/non-cleavable linker. Delivers chemo selectively to antigen-positive cells. Examples: T-DM1, T-DXd, sacituzumab govitecan, enfortumab vedotin, brentuximab vedotin.'],
      ['Synthetic lethality', 'Two genetic changes are individually survivable but lethal in combination. Rationale for PARP inhibitors in BRCA-mutant tumors: BRCA loss + PARP inhibition = unrepairable DSBs.'],
      ['Neoadjuvant vs adjuvant therapy', 'Neoadjuvant = before surgery (shrink tumor, assess in vivo response, downstage). Adjuvant = after surgery (kill residual micrometastases). "Definitive" = the primary treatment when surgery isn\'t used.'],
      ['Tumor mutational burden (TMB)', 'Number of nonsynonymous mutations per Mb of coding sequence. High TMB → more neoantigens → better ICI response. Tissue-agnostic FDA approval for pembrolizumab at TMB ≥10 mut/Mb.'],
      ['MSI-H / dMMR', 'Loss of mismatch repair → many indel mutations at microsatellite repeats. Predicts strong ICI response regardless of tissue of origin. Tissue-agnostic pembrolizumab approval.'],
      ['Cancer vaccines', 'Elicit tumor-antigen-specific T-cell responses. Sipuleucel-T (autologous dendritic cell, prostate) was the first FDA-approved. Personalized neoantigen mRNA vaccines currently in trials with checkpoint inhibitors.'],
      ['Bispecific T-cell engagers (BiTEs)', 'Antibody constructs with two binding arms: one for tumor antigen, one for CD3 on T cells — forcing an immune synapse. Blinatumomab (CD19 × CD3) for B-ALL is the classic; teclistamab (BCMA × CD3) for myeloma.'],
      ['Tyrosine kinase inhibitor (TKI) resistance', 'Common patterns: on-target mutations blocking drug binding (e.g. EGFR T790M, ALK G1202R, BCR-ABL T315I), bypass activation of parallel pathways, or lineage plasticity (e.g. NSCLC → SCLC transformation).'],
      ['Chemo-radiation', 'Concurrent chemotherapy with radiation. Chemo acts as a radiosensitizer. Standard in locally advanced NSCLC, head & neck, cervical, esophageal, anal cancer.'],
      ['Hormone therapy (breast, prostate)', 'Aromatase inhibitors (anastrozole, letrozole) and SERMs/SERDs (tamoxifen, fulvestrant) for HR+ breast. Androgen deprivation (GnRH agonists/antagonists) + androgen receptor blockers (enzalutamide, apalutamide) for prostate.'],
      ['Precision oncology / basket vs umbrella trials', 'Basket trial: one drug across many tumor types with the same target biomarker. Umbrella trial: one tumor type divided into biomarker-defined arms, each with a matched drug.'],
    ],
  },
  {
    name: 'Cancer Biology — Landmark trials (2020s)',
    since: 2,
    cards: [
      ['KEYNOTE-522 (early TNBC)', 'Neoadjuvant pembrolizumab + chemo → surgery → adjuvant pembrolizumab vs chemo alone in stage II-III triple-negative breast cancer. Sponsor: Merck. Improved pCR (~65% vs ~51%) and event-free survival. Approved 2021 as standard of care for early TNBC.'],
      ['KEYNOTE-024 (1L NSCLC PD-L1-high)', 'Pembrolizumab monotherapy vs platinum-doublet chemo in untreated advanced NSCLC with PD-L1 TPS ≥50%, no EGFR/ALK alteration. Merck. 5-yr OS ~32% vs ~16%. Landmark 2016 approval — first single-agent ICI 1L in NSCLC.'],
      ['KEYNOTE-189 (1L nonsquamous NSCLC)', 'Pembrolizumab + carboplatin/pemetrexed vs chemo alone in 1L nonsquamous NSCLC, all PD-L1 levels, no EGFR/ALK. Merck. OS benefit across PD-L1 subgroups. Chemo-IO combo became default when PD-L1 is <50% or high tumor burden.'],
      ['CheckMate 067 (advanced melanoma)', 'Nivolumab + ipilimumab vs nivolumab vs ipilimumab in previously untreated advanced melanoma. BMS. 10-year OS ~43% combo vs ~37% nivo vs ~19% ipi. Foundational combination-checkpoint dataset.'],
      ['RELATIVITY-047 (advanced melanoma)', 'Nivolumab + relatlimab (anti-LAG-3) fixed-dose combo vs nivolumab alone in 1L advanced melanoma. BMS. PFS ~10 vs ~4.6 mo. Approved as Opdualag (2022) — first LAG-3 checkpoint inhibitor.'],
      ['ADAURA (early EGFR NSCLC)', 'Adjuvant osimertinib × 3 years vs placebo after complete resection of stage IB-IIIA EGFR-mutant NSCLC. AZ. DFS HR ~0.20; OS HR ~0.49 at final analysis. Practice-changing 2020 — redefined adjuvant care for resected EGFR NSCLC.'],
      ['FLAURA2 (1L EGFR NSCLC)', 'Osimertinib + platinum/pemetrexed vs osimertinib alone in 1L EGFR-mutant advanced NSCLC. AZ. PFS ~25.5 vs ~16.7 mo; more toxicity. Option for higher-risk EGFR patients (brain mets, L858R).'],
      ['LAURA (stage III EGFR NSCLC)', 'Osimertinib vs placebo after definitive chemoradiation for unresectable stage III EGFR-mutant NSCLC. AZ. PFS ~39 vs ~5.6 mo — dramatic. 2024 readout filled a major gap in stage III EGFR management.'],
      ['MARIPOSA (1L EGFR NSCLC)', 'Amivantamab (EGFR × MET bispecific) + lazertinib vs osimertinib in 1L EGFR-mutant NSCLC. J&J. PFS ~23.7 vs ~16.6 mo but higher infusion reactions, VTE, rash. Alternative 1L for select patients.'],
      ['CROWN (1L ALK NSCLC)', 'Lorlatinib vs crizotinib in 1L ALK+ advanced NSCLC. Pfizer. 5-year PFS ~60% vs ~8% — best PFS reported in advanced NSCLC. Standard 1L for ALK+ NSCLC despite CNS/mood/lipid tox monitoring.'],
      ['ALINA (early ALK NSCLC)', 'Adjuvant alectinib × 2 years vs platinum chemo in resected stage IB (≥4 cm)-IIIA ALK+ NSCLC. Roche. DFS HR ~0.24. Approved 2024 — first adjuvant TKI for ALK+ NSCLC.'],
      ['DESTINY-Breast04 (HER2-low mBC)', 'Trastuzumab deruxtecan (T-DXd) vs physician\'s choice chemo in HER2-low (IHC 1+ or 2+/ISH-) pretreated metastatic breast cancer. AZ/Daiichi. Created a new "HER2-low" treatment class. 2022.'],
      ['DESTINY-Breast06 (HER2-low + ultralow)', 'T-DXd vs chemo in HR+ HER2-low OR HER2-ultralow (IHC 0 with membrane staining) mBC after progression on endocrine therapy. AZ/Daiichi. Extended T-DXd to earlier lines and even lower HER2 expression. 2024.'],
      ['monarchE (early HR+ high-risk BC)', 'Adjuvant abemaciclib × 2 years + endocrine therapy vs endocrine alone in HR+/HER2- node-positive high-risk early breast cancer. Lilly. Persistent iDFS benefit. First adjuvant CDK4/6i approval (2021).'],
      ['NATALEE (early HR+ BC)', 'Adjuvant ribociclib × 3 years + endocrine therapy vs endocrine alone in HR+/HER2- stage II-III early BC — broader population than monarchE. Novartis. iDFS HR ~0.75. Approved 2024.'],
      ['EMERALD (ER+ ESR1-mut mBC)', 'Elacestrant (oral SERD) vs SOC endocrine (fulvestrant or AI) in ER+/HER2- pretreated mBC. Menarini/Stemline. PFS advantage concentrated in ESR1-mutant subgroup. First oral SERD approval (2023).'],
      ['CAPItello-291 (HR+ mBC with pathway alterations)', 'Capivasertib (AKT inhibitor) + fulvestrant vs placebo + fulvestrant in HR+/HER2- mBC after AI progression. AZ. PFS ~7.3 vs ~3.1 mo in AKT/PIK3CA/PTEN-altered subgroup. Approved 2023 with biomarker restriction.'],
      ['CodeBreaK 200 (2L KRAS G12C NSCLC)', 'Sotorasib vs docetaxel in previously treated KRAS G12C-mutant NSCLC. Amgen. Modest PFS benefit, no OS benefit — controversial confirmatory trial that led FDA to require additional dose-comparison work.'],
      ['CodeBreaK 300 (KRAS G12C mCRC)', 'Sotorasib + panitumumab vs sotorasib alone or investigator\'s choice in KRAS G12C chemo-refractory mCRC. Amgen. ORR ~26% combo vs ~6% mono. Combination is the effective regimen in CRC (unlike NSCLC).'],
      ['LIBRETTO-431 (1L RET+ NSCLC)', 'Selpercatinib vs platinum-based chemo ± pembrolizumab in 1L RET fusion-positive advanced NSCLC. Lilly. PFS ~24.8 vs ~11.2 mo. Cemented selpercatinib as 1L standard for RET+ NSCLC.'],
      ['NAPOLI-3 (1L metastatic pancreatic)', 'NALIRIFOX (liposomal irinotecan + oxaliplatin + 5-FU/LV) vs gemcitabine + nab-paclitaxel in 1L metastatic pancreatic adenocarcinoma. Ipsen. Modest OS gain (~11.1 vs ~9.2 mo). New 1L option alongside FOLFIRINOX.'],
      ['ARASENS (mHSPC)', 'Darolutamide + docetaxel + ADT vs docetaxel + ADT in metastatic hormone-sensitive prostate cancer. Bayer. OS benefit. Triplet is now a preferred option for high-volume mHSPC.'],
      ['PROpel (1L mCRPC)', 'Olaparib + abiraterone vs placebo + abiraterone in 1L metastatic castration-resistant prostate cancer, all-comers. AZ/Merck. rPFS benefit; FDA restricted approval to BRCA1/2-mutated subset (2023) — trial/label disconnect.'],
      ['TALAPRO-2 (1L mCRPC)', 'Talazoparib + enzalutamide vs placebo + enzalutamide in 1L mCRPC. Pfizer. rPFS benefit, larger in HRR-mutated. FDA also restricted approval to HRR-mutated — same pattern as PROpel.'],
      ['INDIGO (IDH-mut low-grade glioma)', 'Vorasidenib (dual IDH1/2 inhibitor) vs placebo in residual/recurrent grade 2 IDH1/2-mutant glioma after resection. Servier. PFS ~27.7 vs ~11.1 mo. First targeted therapy for this subtype. Approved 2024.'],
      ['CheckMate 816 (resectable NSCLC)', 'Neoadjuvant nivolumab + chemo (3 cycles) vs chemo alone in resectable stage IB-IIIA NSCLC. BMS. pCR ~24% vs ~2%; improved EFS. Approved 2022 — established neoadjuvant IO for resectable NSCLC.'],
      ['KEYNOTE-671 (perioperative NSCLC)', 'Neoadjuvant pembrolizumab + chemo → surgery → adjuvant pembrolizumab vs neoadjuvant chemo alone → surgery → placebo, in resectable stage II-IIIB NSCLC. Merck. EFS and OS benefit. Extended IO to the full perioperative window.'],
      ['ADRIATIC (limited-stage SCLC)', 'Consolidation durvalumab (± tremelimumab) vs placebo after concurrent chemoradiation in limited-stage SCLC. AZ. Median OS ~55.9 vs ~33.4 mo. Practice-changing 2024 — first IO benefit in LS-SCLC.'],
      ['POLARIX (1L DLBCL)', 'Polatuzumab vedotin (anti-CD79b ADC) + R-CHP vs R-CHOP in 1L DLBCL. Roche. PFS HR ~0.73; OS neutral. Selective new standard for IPI 2+ high-risk DLBCL (subgroup benefit largely in ABC subtype).'],
      ['ZUMA-7 (2L LBCL)', 'Axicabtagene ciloleucel (axi-cel) vs standard salvage chemo + auto-SCT in 2L R/R large B-cell lymphoma refractory or relapsing within 12 months. Kite/Gilead. EFS and OS benefit. Moved CAR-T from 3L to 2L in eligible patients.'],
      ['CARTITUDE-4 (R/R myeloma)', 'Ciltacabtagene autoleucel (cilta-cel) vs pomalidomide-based SOC in R/R multiple myeloma after 1-3 prior lines, lenalidomide-refractory. J&J/Legend. PFS HR ~0.26 — dramatic. 2024 expansion of CAR-T to earlier myeloma lines.'],
      ['MajesTEC-1 (R/R myeloma)', 'Teclistamab (BCMA × CD3 bispecific T-cell engager) in triple-class-exposed R/R multiple myeloma. J&J. ORR ~63% in a heavily pretreated population. Approved 2022 — first BCMA BiTE.'],
      ['SPOTLIGHT / GLOW (1L gastric)', 'Zolbetuximab (anti-CLDN18.2 mAb) + chemo vs chemo alone in 1L HER2-negative, CLDN18.2+ (≥75% of tumor cells staining) advanced gastric/GEJ adenocarcinoma. Astellas. OS benefit. Approved 2024 — new biomarker-defined gastric subset.'],
      ['IMbrave150 (1L unresectable HCC)', 'Atezolizumab + bevacizumab vs sorafenib in 1L unresectable HCC. Roche. Median OS ~19.2 vs ~13.4 mo. 2020 practice change — first ICI-based combo standard in HCC.'],
      ['CheckMate 9DW (1L unresectable HCC)', 'Nivolumab + ipilimumab vs investigator\'s choice (lenvatinib or sorafenib) in 1L unresectable HCC. BMS. OS benefit. Approved 2024 as second ICI-based option in 1L HCC (avoids anti-VEGF bleeding risk).'],
      ['CheckMate 649 (1L gastric)', 'Nivolumab + chemo vs chemo alone in 1L HER2-negative advanced gastric/GEJ/esophageal adenocarcinoma. BMS. OS benefit concentrated in PD-L1 CPS ≥5; FDA label ultimately narrowed accordingly (2024 update).'],
      ['LITESPARK-005 (2L+ ccRCC)', 'Belzutifan (HIF-2α inhibitor) vs everolimus in previously treated advanced clear cell RCC. Merck. PFS benefit, ORR advantage, OS non-significant. Also approved for VHL-associated tumors.'],
      ['Dostarlimab in dMMR rectal (Cercek/MSK)', 'Neoadjuvant single-agent dostarlimab (anti-PD-1) in locally advanced dMMR/MSI-H rectal adenocarcinoma. GSK. 100% clinical complete response in initial pilot, replicated as cohort expanded. Enables non-operative management in this curable subset — organ-preserving approach.'],
      ['ADAURA-2 / other adjuvant / MRD ctDNA notes', 'A recurring theme in 2020s trials: minimal residual disease (MRD) detected by ctDNA is being used to select patients for adjuvant therapy escalation (e.g. DYNAMIC in stage II colon, IMvigor011 in urothelial). Watch this space — biomarker-guided adjuvant IO is the next frontier.'],
    ],
  },
];
